'use strict';

// 设置视图只接收设置快照，不读取宿主和运行状态。
function settingsView(settings) {
        return [
            '<div class="inline-drawer">',
            '  <div class="inline-drawer-toggle inline-drawer-header">',
            '    <b>MVU转数据库</b>',
            '    <div class="inline-drawer-icon fa-solid fa-circle-chevron-down down"></div>',
            '  </div>',
            '  <div class="inline-drawer-content">',
            '    <div class="mvu2shujuku-card">',
            '      <div class="mvu2shujuku-row">',
            '        <span class="mvu2shujuku-label">输入来源（二选一）</span>',
            '        <label><input type="radio" name="mvu2shujuku-source" value="character" checked /> 酒馆角色卡</label>',
            '        <label><input type="radio" name="mvu2shujuku-source" value="file" /> 本地文件</label>',
            '      </div>',
            '      <div id="mvu2shujuku-char-area" class="mvu2shujuku-source-area">',
            '        <div class="mvu2shujuku-row">',
            '          <label class="mvu2shujuku-label" for="mvu2shujuku-char-select">选择角色卡</label>',
            '          <input id="mvu2shujuku-char-search" type="text" placeholder="搜索角色…" title="输入角色名过滤下拉列表" />',
            '          <select id="mvu2shujuku-char-select" title="从酒馆角色列表选择要转换的角色卡"></select>',
            '          <button id="mvu2shujuku-char-refresh" class="menu_button" title="重新读取 SillyTavern 角色列表">刷新角色列表</button>',
            '        </div>',
            '      </div>',
            '      <div id="mvu2shujuku-file-area" class="mvu2shujuku-source-area" style="display:none">',
            '        <div class="mvu2shujuku-row">',
            '          <label class="mvu2shujuku-label">选择本地文件</label>',
            '          <button id="mvu2shujuku-pick-file" class="menu_button" title="从磁盘选择 .json / .png 角色卡文件">选择文件…</button>',
            '          <input id="mvu2shujuku-file" type="file" accept=".json,.png,application/json,image/png" hidden />',
            '          <span id="mvu2shujuku-file-name" class="mvu2shujuku-hint"></span>',
            '        </div>',
            '      </div>',
            '      <div class="mvu2shujuku-row mvu2shujuku-mode-group">',
            '        <span class="mvu2shujuku-label" title="模板同时写入 DDL 与 SQL 示例；AI 实际输出 insertRow DSL 还是 SQL，由 SP·数据库 插件自身的填表模式决定，转换器无需选择">填表模式</span>',
            '        <span class="mvu2shujuku-hint">双模式（跟随插件当前设置）</span>',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label class="mvu2shujuku-label" for="mvu2shujuku-profile-select">转换配置</label>',
            '        <select id="mvu2shujuku-profile-select" title="可选：把已保存的表格更新参数和外部表来源应用到本次新转换"></select>',
            '        <button id="mvu2shujuku-profile-delete" class="menu_button" disabled title="只删除转换配置，不删除角色卡或数据库预设">删除配置</button>',
            '      </div>',
            '      <div class="mvu2shujuku-help">新卡无需选择配置：下载角色卡/模板或保存到 SillyTavern 时，会按原角色卡名自动保存。重新转换时可在此主动选择已有配置。</div>',
            '      <div class="mvu2shujuku-row">',
            '        <label class="mvu2shujuku-check-label" title="控制生成的表格 DDL 是否带 CHECK 约束（数值范围、枚举、JSON 表 json_valid）。关闭后仅保留列类型与默认值，新建聊天时 SQLite 不再做这些校验；改动需重新转换生效"><input type="checkbox" id="mvu2shujuku-ddl-check" ' + (settings.ddlIncludeCheck !== false ? 'checked' : '') + ' /> 转换时在表格 DDL 中加入 CHECK 约束（数值范围/枚举/json_valid）</label>',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label class="mvu2shujuku-check-label" title="仅把无 else、无嵌套、静态字段与字面量比较的简单 EJS if 转成数据库 <if db>；循环、函数和复杂分支仍保留 EJS"><input type="checkbox" id="mvu2shujuku-ejs-translate" ' + (settings.translateSimpleEjs ? 'checked' : '') + ' /> 尝试把安全的简单 EJS 条件翻译为数据库语法（实验性）</label>',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label class="mvu2shujuku-label" for="mvu2shujuku-shim">MVU 兼容层</label>',
            '        <select id="mvu2shujuku-shim">',
            '          <option value="auto" ' + (settings.installMvuShim === 'auto' ? 'selected' : '') + '>自动（检测到 MVU API 才装）</option>',
            '          <option value="yes" ' + (settings.installMvuShim === 'yes' ? 'selected' : '') + '>总是安装</option>',
            '          <option value="no" ' + (settings.installMvuShim === 'no' ? 'selected' : '') + '>不安装</option>',
            '        </select>',
            '      </div>',
            '      <div class="mvu2shujuku-help">',
            '        MVU（MagVarUpdate）是旧角色卡用的变量框架：游戏状态存在 <code>stat_data</code>，脚本/状态栏通过 MVU API 读写变量',
            '        （入口是全局对象 <code>Mvu</code>，方法 <code>getMvuData</code> / <code>replaceMvuData</code>）。',
            '        转换后数据桥会提供同名兼容对象，把旧脚本的 MVU API 调用自动翻译成数据库操作，旧脚本才能继续工作。',
            '        若卡片脚本没用到 MVU API，选“不安装”即可。',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label title="状态栏刷新由数据库表格更新回调驱动；此选项额外在 AI 回复结束时补一次刷新并处理消息里的 <UpdateVariable>/<json_patch> 更新块"><input type="checkbox" id="mvu2shujuku-placeholder" ' + (settings.appendPlaceholder !== false ? 'checked' : '') + ' /> 表格更新后自动刷新状态栏（含消息收尾兜底）</label>',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label title="勾选后输出 [mvu2shujuku][debug] 调试日志（排查问题时开启，平时关闭）"><input type="checkbox" id="mvu2shujuku-debug" ' + (settings.debug ? 'checked' : '') + ' /> 输出 debug 日志</label>',
            '      </div>',
            '      <div class="mvu2shujuku-help">',
            '        状态栏刷新与 MVU 原版一致：数据库一有变动就广播 <code>mag_variable_update_ended</code>（VARIABLE_UPDATE_ENDED），前端原 eventOn 监听直接生效。',
            '        勾选上方选项后，还会在每次 AI 回复结束时补一次刷新，并顺带处理开场白/消息里的 <code>&lt;UpdateVariable&gt;</code> / <code>&lt;json_patch&gt;</code> 旧式更新块。',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <label class="mvu2shujuku-label" for="mvu2shujuku-png">输出格式</label>',
            '        <select id="mvu2shujuku-png">',
            '          <option value="auto" ' + (settings.asPng === 'auto' ? 'selected' : '') + '>跟随输入（PNG 输入 → PNG 输出）</option>',
            '          <option value="json" ' + (settings.asPng === 'json' ? 'selected' : '') + '>总是 JSON</option>',
            '          <option value="png" ' + (settings.asPng === 'png' ? 'selected' : '') + '>总是 PNG</option>',
            '        </select>',
            '      </div>',
            '      <div class="mvu2shujuku-row">',
            '        <button id="mvu2shujuku-convert-current" class="menu_button">转换所选角色卡</button>',
            '        <button id="mvu2shujuku-convert-file" class="menu_button" disabled title="从磁盘选择 .json / .png 角色卡文件">转换所选文件</button>',
            '        <button id="mvu2shujuku-clear" class="menu_button">清空结果</button>',
            '      </div>',
            '      <div class="mvu2shujuku-result"></div>',
            '      <div id="mvu2shujuku-actions" class="mvu2shujuku-row">',
            '        <div id="mvu2shujuku-downloads" class="mvu2shujuku-downloads mvu2shujuku-row"></div>',
            '        <button id="mvu2shujuku-save-card" class="menu_button" style="display:none" title="转换完成后出现：把角色卡保存进 sillytavern 角色列表，并顺带把表格模板存为插件预设">保存角色卡和模板到sillytavern</button>',
            '      </div>',
            '      <div class="mvu2shujuku-hint">',
            '        前提：已安装 SP·数据库插件（不自动安装，也不迁移旧聊天）。数据桥已写入转换后的角色卡，不需要手动导入；单独下载的 .js 只是供开发者查看和调试的源码备份，不是酒馆助手 .json 导入包。',
            '      </div>',
            '    </div>',
            '  </div>',
            '</div>',
        ].join('\n');
    }

module.exports = settingsView;
